version: '3.8'
services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
